config/routes.rb
GCMServerTest::Application.routes.draw do

  get 'smart_out/index'

  root to: 'smart_out#index', as: 'index'

  match 'category_type/:type' => 'types#category_by_type'
  get 'users/:user_id/coupons/by_place/:location', to: 'coupons#by_place'
  get 'users/:user_id/coupons/by_likes', to: 'coupons#by_likes'
  get 'users/:user_id/coupons/by_random', to: 'coupons#by_random'

  resources :users do
    resources :coupons, only: [:index]
    member do
      put 'add_entity'
    end
  end

  resources :entities do
    resources :coupons, except: [:destroy]
  end

  resources :categories, except: [:show]

  resources :types, except: [:show] do
    member do
      get 'category_by_type'
    end
  end

  resources :locations, only: [:index, :new, :create]

end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  # respond_to :html
  respond_to :json
  def index
    @types = Type.all
    # respond_with(@types) do |format|
    #   format.html { render partial: 'show', layout: false }
    # end
    respond_with @types
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new params[:type]
    if @type.save
      # respond_with do |format|
      #   format.html{ redirect_to types_path, notice: 'New type was created' }
      # end
      flash[:notice] =  'New type was created'
      respond_with @type
    else
      flash[:errors] = "#{@type.errors}"
      respond_with @type
    end
  end

  def category_by_type
    @categories = Type.where('type_name = ?',params[:type])
                      .select('category_name, category_description')
                      .joins :categories
    # respond_with(@categories) do |format|
    #   format.html { render partial: 'categories/categories',
    #                        locals: { type: params[:type] },
    #                        layout: false
    #   }
    # end
    respond_with @categories
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<% errors = @type.errors %>
<%= form_for @type do |form| %>
    <%= error_div errors do %>
        <%= content_tag :h2, "#{pluralize(errors.count, 'error')} prohibited this user from being saved:" %>
        <%= error_list errors %>
    <% end %>
    <%= form.label :type_name %>
    <%= form.text_field :type_name %>

    <%= form.label :type_description %>
    <%= form.text_field :type_description %>

    <%= form.submit 'Nuevo tipo' %>
<% end %>

app/views/types/_show.html.erb
<h1>Types</h1>
<section class="types" id="types">
  <% @types.each do |type| %>
      <div class="type" data-name=<%= type %>>
        <h2><%= type %></h2>
      </div>
  <% end %>
</section>

app/views/types/index.html.erb
<%= render 'show' %>
<%= link_to 'New Type', new_type_path %>