config/routes.rb
GCMServerTest::Application.routes.draw do

  get 'smart_out/index'

  root to: 'smart_out#index', as: 'index'

  match 'category_type/:type' => 'types#category_by_type'
  get 'users/:user_id/coupons/by_place/:location', to: 'coupons#by_place'
  get 'users/:user_id/coupons/by_likes', to: 'coupons#by_likes'
  get 'users/:user_id/coupons/by_random', to: 'coupons#by_random'

  resources :users do
    resources :coupons, only: [:index]
    member do
      put 'add_entity'
    end
  end

  resources :entities do
    resources :coupons, except: [:destroy]
  end

  resources :categories, except: [:show]

  resources :types, except: [:show] do
    member do
      get 'category_by_type'
    end
  end

  resources :locations, only: [:index, :new, :create]

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

    # ===========================Attributes=====================================
  	attr_accessible :entity_id, :coupon_msg, :coupon_name, :coupon_num,
  					:coupon_image
	  has_attached_file :coupon_image,
  		:styles => { :small => '300x300>' },
  		:url  => '/assets/users/:id/:style/:basename.:extension',
      :path => ':rails_root/public/assets/users/:id/:style/:basename.:extension',
      :default_url => ''
    # ===========================end attributes=================================

    # ===========================model validations=============================
    validates_attachment_size :coupon_image, less_than: 2.megabytes
    validates_attachment_content_type :coupon_image, :content_type => %w(image/jpeg image/png)
    {
      coupon_msg: 'Which is about your coupon?',
      coupon_name: 'Which is the title of your coupon?',
      coupon_num: 'How many coupons do you want to make?',
    }.each do |attr, msg|
    	validates_presence_of attr, message: "#{msg}"
    end
      validates_numericality_of :coupon_num, :only_integer => true,
                                greater_than_or_equal_to: 10,
                                message: 'Sorry your promotion has to be for more than 10 people'
      validates_length_of :coupon_msg, within:10..50,
                          too_long: 'The coupon message length must be less than 50',
                          too_short: 'The coupon message length must be greater than 10'
      validates_length_of :coupon_name, within: 2..20,
                          too_long: 'maximum value size is 20 chars',
                          too_short: 'the value length must be at least 2 chars'
    # =============================end validations==============================

    # =============================model relationship===========================
    belongs_to :entity, class_name: 'Entity', foreign_key: 'entity_id',
                inverse_of: :coupons
    has_many :user_coupons
    has_many :users, through: :user_coupons
    # =============================end relationship=============================

    # convert coupon object into a hash to send as json
  	def to_h
=begin
  		coupon_hash = Hash.new
  		coupon_hash[:coupon_name] = self.coupon_name
  		coupon_hash[:coupon_msg] = self.coupon_msg
  		coupon_hash[:coupon_image] = self.coupon_image unless self.coupon_image.url.empty?
  		coupon_hash
=end
      coupon_image = self.coupon_image unless self.coupon_image.url.empty?
      {
        coupon_name: self.coupon_name,
        coupon_msg: self.coupon_msg,
        coupon_image: coupon_image
      }.to_json
  	end

  	private
    # task to be executed every day at 12am (midnight)
    # update every coupon state to false which its state is true, it means every
    # expire every coupon per day
  	def self.change_state
  		Coupon.update_all({ :coupon_state => false }, { :coupon_state => true })
  		puts 'hola update'
  	end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  # cuando el request es POST y es enviado vía JSON desde el celular evita la validación
  # del token de autenticidad
	#skip_before_filter :verify_authenticity_token,
	#if: Proc.new { |_user| _user.request.format == 'application/json' }
  before_filter :load_entity, except: [:index, :by_place, :by_likes, :by_random]
  before_filter :auth_user, only: [:index, :by_place, :by_likes, :by_random]
  respond_to :html
  respond_to :json, only: :index

  # encuentra 5 cupones disponibles de manera aleatoria, directamente sobre los gustos de cada usuario
  def index
=begin QUERY
  coupons.entity_id == entity.id and
  entity.id == user_entity.entity_id and
  user_entity.user_id == user.id and
  coupons.coupon_state == true
  5 random entities
=end
    user_id = params[:user_id]
    if user_id
      @coupons = Coupon.joins(entity: :users).where(coupon_state: true, users: { id: user_id } ).random(5)
      respond_with @coupons do |format|
        format.html { render layout: false}
      end
    else
      load_entity
      @coupons = @entity.coupons
    end
  end

  # encuentra 5 cupones disponibles de manera aleatoria, de acuerdo a un lugar (:location)
  def by_place
=begin QUERY
    coupons.entity_id == entity.id and
    entity.id == entity_location.entity_id and
    entity_location.location_id == location.id and
    location.name == location_from_params and
    coupon.coupon_state = true
    5 random entities
=end
    @coupons = Coupon.joins(entity: :locations).where(coupon_state: true, locations: { name: params[:location] }).random(5)
  end

  # encuentra 5 cupones disponibles de manera aleatoria, teniendo en cuenta los
  # los gustos de cada usuario ( por categorías relacionadas a los negocios (:entities)
  # seleccionados )
  def by_likes

  end

  # encuentra 5 cupones disponibles de manera aleatoria
  def by_random

  end

  def new
    @coupon = @entity.coupons.new
  end

  # POST /coupons
 	# POST /coupons.json
  def create
  	@coupon = @entity.coupons.new params[:coupon]
    if @coupon.save
      respond_with do |format|
        format.html{ redirect_to entity_coupons_path(@entity), notice: 'Your new coupon was created successfully' }
      end
    else
      respond_with(@coupon, notice: @coupon.errors)
    end
  end

def show
=begin
		devices = Gcm::Device.find(5)
		notification = Gcm::Notification.new
		notification.device = devices
		notification.collapse_key = "New Coupon"
		notification.delay_while_idle = true
		@coupon = Coupon.select("coupon_msg,coupon_name").find(1)
		notification.data = {:registration_ids => [devices.registration_id], :data => @coupon.to_h}
		notification.save
		Gcm::Notification.send_notifications
		render nothing: true
=end
  end
  
  private
    # cuando estamos tratando sobre los negocios ( :entities ) y no sobre los usuarios,
    # necesitamos cargar previamente a cada acción el negocio sobre el cual
    # estamos trabajando
    def load_entity
      #@entity = Entity.joins(:coupons).find(params[:entity_id])
      @entity = Entity.find params[:entity_id]
    end

end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<% errors = @coupon.errors %>
<%= form_for [@entity, @coupon] do |form| %>
    <%= error_div errors do %>
        <%= content_tag :h2, "#{pluralize(errors.count, 'error')} prohibited this user from being saved:" %>
        <%= error_list errors %>
    <% end %>
    <%= form.label :coupon_name %>
    <%= form.text_field :coupon_name %>
    <%= form.label :coupon_msg %>
    <%= form.text_field :coupon_msg %>
    <%= form.label :coupon_num %>
    <%= form.number_field :coupon_num, min: 1%>
    <section id="img_container" style="display: none">

    </section>
    <%= form.label :coupon_image %>
    <%= form.file_field :coupon_image, id:'img_change' %>
    <%= form.submit %>
<% end %>

app/views/coupons/index.html.erb
<% if @entity %>
  <p id="notice"><%= notice %></p>
  <h1> <%= @entity.entity_name %> Coupons </h1>
<% else %>
  <h1> Available Coupons for you </h1>
<% end %>
<% unless @coupons.empty? %>
    <section class="coupons">
    <% @coupons.each do |coupon| %>
      <div class="coupon">
        <h2 class="title"><%= coupon.coupon_name %></h2>
        <p class="description"><%= coupon.coupon_msg %></p>
        <% if not coupon.coupon_image.url.empty? %>
            <div class="img">
              <%= image_tag coupon.coupon_image.url(:small) %>
            </div>
        <% else %>
            <!-- default img -->
        <% end %>
        <div class="available">
          <%= pluralize(coupon.coupon_num, 'Coupon') %> Available
        </div>
      </div>
    <% end %>
    </section>
<% else %>
  <% if @entity %>
    <h2 class="no_coupons"> OH!! i can't see any coupon, lets start and make one, be more Awesome </h2>
  <% end %>
<% end %>
<%= link_to 'Become more Awesome, create a new Coupon', new_entity_coupon_path(@entity) if @entity %>