config/routes.rb
GCMServerTest::Application.routes.draw do

  get 'smart_out/index'

  root to: 'smart_out#index', as: 'index'

  match 'category_type/:type' => 'types#category_by_type'
  get 'users/:user_id/coupons/by_place/:location', to: 'coupons#by_place'
  get 'users/:user_id/coupons/by_likes', to: 'coupons#by_likes'
  get 'users/:user_id/coupons/by_random', to: 'coupons#by_random'

  resources :users do
    resources :coupons, only: [:index]
    member do
      put 'add_entity'
    end
  end

  resources :entities do
    resources :coupons, except: [:destroy]
  end

  resources :categories, except: [:show]

  resources :types, except: [:show] do
    member do
      get 'category_by_type'
    end
  end

  resources :locations, only: [:index, :new, :create]

end

app/models/category.rb
class Category < ActiveRecord::Base

    # ===========================Attributes=====================================
    attr_accessible :category_name, :category_description, :picture
    has_attached_file :picture,
                      :styles => { :medium => '400x400>' },
                      :url  => '/assets/images/categories/:id/:basename.:extension',
                      :path => ':rails_root/app/assets/images/categories/:id/:basename.:extension',
                      :default_url => ''
    # ===========================end attributes=================================

    # ===========================model validations=============================
    validates_uniqueness_of :category_name, message: 'This category name already exist'
    validates_presence_of :category_name, message: 'Category name can\'t be blank'
    validates_length_of :category_name, minimum: 3 ,too_short: 'Category name must have at least 3 characters length'
    validates_attachment_size :picture, less_than: 3.megabytes
    validates_attachment_content_type :picture, :content_type => %w(image/jpeg image/png)
    # =============================end validations==============================

    # =============================model relationship===========================
    has_many :type_categories
    has_many :types, through: :type_categories
    has_many :entity_categories
    has_many :entities, through: :entity_categories
    # =============================end relationship=============================

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # respond_to :html
  respond_to :json

  def index
    @categories = Category.all
    respond_with @categories
    # respond_with(:index, locals: { type: nil })
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new params[:category]
    if @category.save
      # respond_with do |format|
      #   format.html { redirect_to categories_path, notice: "#{@category.category_name} creada" }
      # end
      flash[:notice] = "#{@category.category_name} creada"
      respond_with @category
    else
      # respond_with(@category, notice: @category.errors)
      flash[:errors] = "#{@category.errors}"
      respond_with @category
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def _type(type)
    if type
      type
    else
      ''
    end
  end
end

app/views/categories/_categories.html.erb
<h1>
  <%= _type(type) %> Categories
</h1>
<section class="categories">
  <% @categories.each do |category| %>
      <div class="category"
           title="<%= category.category_description %>"
           data-category="<%= category.category_name %>"
           <% unless _type(type).empty? %>
             data-category-type="<%= type %>"
           <% end %>
      >
        <h2><%= category.category_name %></h2>
      </div>
  <% end %>
</section>

app/views/categories/_form.html.erb
<% errors = @category.errors %>
<%= form_for @category do |form| %>
    <%= error_div errors do %>
        <%= content_tag :h2, "#{pluralize(errors.count, 'error')} prohibited this user from being saved:" %>
        <%= error_list errors %>
    <% end %>
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>

    <%= form.label :category_description %>
    <%= form.text_field :category_description %>

    <%= form.submit 'Nueva Categoria' %>
<% end %>

app/views/categories/index.html.erb
<%= render partial: 'categories', locals: { type: type } %>
<%= link_to 'New Category', new_category_path %>